version: 2.1
jobs:
  build:
    working_directory: ~/repo/art-social-app
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test