version: 2.1

jobs:
  build:
    working_directory: ~/repo/art-social-app
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-
          paths:
            - node_modules

  test:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - run:
          name: Change directory
          command: cd ~/repo/art-social-app
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test

  deploy:
    docker:
      - image: docker:latest
    steps:
      - run:
          name: Set Version Tag
          command: echo "VERSION_TAG=$(git rev-parse --short HEAD)" >> $BASH_ENV
      - run:
          name: Build and Tag Docker Image
          command: |
            docker build -t my-app:$VERSION_TAG .

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
